spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    default: local
    include:
      - aws
      - oauth

app:
  token:
    SECRET_KEY: ${SECRET_KEY:default_secret_key}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://127.0.0.1:13306/mydatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:myuser}
    password: ${MYSQL_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:/uniondb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  # TODO: 테스트할 때 환경 변수 설정 -> 왜 동작을 안하지... (멘토님한테 물어봐야 겠다...)
#  aws:
#    credentials:
#      accessKey: ${AWS_ACCESS_KEY:test_key}
#      secretKey: ${AWS_SECRET_KEY:test_secret}
#  SECRET_KEY: ${SECRET_KEY:test_secret_key}

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
